# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c8d06a71e53448f9ed61a354a7a70479"
name = "cnc-custom-app"
application_url = "https://proteam-sports-custome-app-md-01ab47430902.herokuapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locales,read_locations,read_orders,read_product_listings,read_products,read_publications,read_script_tags,write_content,write_delivery_customizations,write_inventory,write_locations,write_products,write_publications,write_script_tags,write_shipping"

[auth]
redirect_urls = [
  "https://pera-integration-custom-app-8fec38b7e201.herokuapp.com/api/auth"
]
